### ISSUE TITLE
Bogus illegal instruction and SIGSEGV errors when debugging in Netbeans

### ISSUE THREAD

**Issue by X547** [trungnt2910/gdb-haiku#1]
`gdb-15-haiku-v11` 861b4bb3113

Netbeans project (includes makefile and binaries): 
[MinApp-Netbeans.zip](https://github.com/user-attachments/files/16340211/MinApp-Netbeans.zip)

**Comment by trungnt2910** [comment]
Can you try e7f39a770 to see if that's fixed?

**Comment by X547** [comment]
> Can you try [e7f39a7](https://github.com/trungnt2910/gdb-haiku/commit/e7f39a770109c0f2f41854e66712c515290d5021) to see if that's fixed?

Yes, it fixes problem.

**Comment by trungnt2910** [comment]
Integrated into the recently pushed patches. Closing.
