### ISSUE TITLE
Pausing program or adding breakpoints during execution when using remote Netbeans debug cause debugged program to exit

### ISSUE THREAD

**Issue by X547** [trungnt2910/gdb-haiku#3]
Local debugging work fine.

**Comment by trungnt2910** [comment]
Theoretically pausing programs should be fixed with the latest commits.

**Comment by X547** [comment]
Issue is still present in `gdb-15-haiku-v12` e7f39a77010.

**Comment by trungnt2910** [comment]
The commit that would theoretically fix the issue is not present in your version:

https://github.com/trungnt2910/gdb-haiku/commit/149b11665ab4733d70b81add268417cd5b61523e

I have not tested your use case yet.

**Comment by trungnt2910** [comment]
Please check the latest version. I have been able to consistently use Ctrl + C.

![image](https://github.com/user-attachments/assets/14b18fbc-a0db-4287-a00b-2df2c0ed0b65)

**Comment by X547** [comment]
I managed to build gdb-15-haiku-v13 https://github.com/trungnt2910/gdb-haiku/commit/155bd98a6f241e8a07239333b25608523e882bb6 with positive error codes.

Now it do not exit on pause button click, but it do not respond to any actions such as setting breakpoints during debugging or terminating program. Local debugging still works fine.

https://gist.github.com/X547/0cd9369698b987d82da3570d34017592

**Comment by X547** [comment]
Problem is not observed anymore in `gdb-15-haiku-v14` cf1ccefc81d.
