### ISSUE TITLE
[REGRESSION] a lot of SIGTRAP events are generated after triggering interrupt

### ISSUE THREAD

**Issue by X547** [trungnt2910/gdb-haiku#5]
gdb-15-haiku-v13 https://github.com/trungnt2910/gdb-haiku/commit/155bd98a6f241e8a07239333b25608523e882bb6, local debugging in Netbeans. Issue is not present in gdb-15-haiku-v12 https://github.com/trungnt2910/gdb-haiku/commit/e7f39a770109c0f2f41854e66712c515290d5021.

A lot of SIGTRAP notifications are produced after triggering breakpoint. You need to click discard and continue button a lot of times. But initial SIGTRAP notification in program relocated is disappeared.

For GUI application SIGTRAP is usually triggered on wait for port message syscall.

**Comment by trungnt2910** [comment]
Your build was not the latest commit at the time this issue was open. Please try cf1ccef.

**Comment by X547** [comment]
Fix confirmed in `gdb-15-haiku-v14` cf1ccefc81d.
